---
- name: Install Docker and Start docker service on localhost
  hosts: localhost,docker_server 
  become: true
  tasks:
    - name: Docker Installation
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Enable and start docker service
      service: 
        name: docker
        state: started
        enabled: true

- name: Install Docker and Start docker service on localhost and remote server
  hosts: localhost,docker_server 
  become: true
  tasks:
    - name: Docker Installation
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Enable and start docker service
      service: 
        name: docker
        state: started
        enabled: true
# ----------------------------------------
- name: Build Docker Image
  hosts: localhost # if we write docker_server then we dont have any files yet and to automate the process we use ansible localhost
  become: true
  vars_files:
    - ./vars.yml

  tasks:
    - name: Docker Installation
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Enable and start docker service
      service: 
        name: docker
        state: started
        enabled: true

    - name: Build Image
      command: docker build -t {{docker_username}}/{{docker_repo}}:{{docker_tag}} .

    - name: Docker login 
      shell: echo "{{ DOCKER_PAT }}" | docker login -u {{docker_username}} --password-stdin

    - name: Push Docker Image
      command: docker push {{docker_username}}/{{docker_repo}}:{{docker_tag}}


# ----------------------------------------
- name: Pull Image and Run Docker Container
  hosts: docker_server
  become: true
  vars_files:
    - ./vars.yml
  
  tasks:
    - name: Docker Installation
      yum:
        name: docker.io
        state: present
        update_cache: yes

    - name: Enable and start docker service
      service: 
        name: docker
        state: started
        enabled: true

    - name: pull docker image from docker hub
      command: docker pull {{docker_username}}/{{docker_repo}}:{{docker_tag}}
    
    - name: Remove exising docker container if exists
      command: docker rm -f c1

    - name: Run docker container
      command: docker run -dit -p {{target_port}}:{{docker_container_port}} --name c1 {{docker_username}}/{{docker_repo}}:{{docker_tag}}

# ----------------------------------------
- name: Decrypting nginx with jinja2 configuration
  hosts: nginx_server
  become: true
  vars_files:
    - ./vars.yml

  tasks:
    - name: Install nginx Ubuntu
      apt:
        name: nginx 
        state: present

    - name: Install required packages
      apt:
        name:
          - certbot
          - python3-certbot-nginx 
        state: present

    - name: Installation of SSL Certificate
      command: > 
        certbot certonly --nginx -d {{domain_name}} 
        --email {{email}} 
        --agree-tos
        --non-interactive       

    # - name: Copying j2 template to nginx configuration
    #   template:
    #     src: nginx.conf.j2
    #     dest: /etc/nginx/nginx.conf
    #   notify: Reload nginx

    - name: Enable nginx service
      service:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: Reload nginx
      service: 
        name: nginx
        state: restarted